import React from "react";
import ReactDOM from "react-dom";
import * as Sentry from "@sentry/react";
// import * as FullStory from "@fullstory/browser";
// import SentryFullStory from "@sentry/fullstory";
import { Integrations as TracingIntegrations } from "@sentry/tracing";
import "./index.css";
import App from "./App";

// FullStory.init({ orgId: "164KVD" });

Sentry.init({
  dsn: "https://4bb8adf9789742c590395533a427a0e1@leeandher.ngrok.io/8",
  integrations: [
    // new SentryFullStory("leander-test"),
    new TracingIntegrations.BrowserTracing({
      tracingOrigins: ["localhost", "catfact.ninja", /^\//],
      shouldCreateSpanForRequest: (_url) => true,
    }),
  ],
  tracesSampleRate: 1.0,
  beforeSend(event, hint) {
    // Filter out test events generated by error-generator.sentry.dev
    // These are synthetic test events, not real application errors.
    
    // Check if transaction name indicates a test event
    const transaction = event.transaction;
    if (transaction && transaction.startsWith("test-transaction-")) {
      return null;
    }
    
    // Check if user ID indicates a test event
    const user = event.user;
    if (user && user.id && String(user.id).startsWith("test-user-")) {
      return null;
    }
    
    return event;
  },
});

Sentry.setContext("session_id", "12123");

ReactDOM.render(<App />, document.getElementById("root"));
